site_name: Dragon of Icespire Peak
nav: 
    - Home: index.md
    - Game: game.md
    - Players:
      - Finn: people/finn.md
      - Pulse: people/pulse.md
      - Robo Dan: people/robodan.md
      - Smogg Fracks: people/smogg.md
      - Wyatt: people/wyatt.md
      - Zim Wicketbooster: people/zim.md
    - Sessions:
      - '20200921: Manticore': sessions/20200921.md
      - '20200930: Mimic': sessions/20200930.md
      - '20201012: Ranch I': sessions/20201012.md
      - '20201021: Ranch II': sessions/20201021.md
theme:
    name: material
    highlightjs: true
    nav_style: dark
    